[利用python数据分析panda学习笔记之基本功能](https://www.cnblogs.com/lanjianhappy/p/7403600.html)

#### 1 重新生成索引 如果某个索引值不存在就引入缺失值

from pandas import Series,DataFrame
import pandas as pd
import numpy as np
obj=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
print(obj)

#重新生成索引
obj2=obj.reindex(['a','b','c','d','e'])
print(obj2)

In [4]:
# a使用method的ffill可以实现前向值填充，效果如下
#前向填充
obj3=Series(['blue','purple','yellow'],index=[0,2,4])
print(obj3)
obj3.reindex(range(6),method='ffill')
print(obj3)

0      blue
2    purple
4    yellow
dtype: object
0      blue
2    purple
4    yellow
dtype: object


In [5]:
# b:对于dataframe使用reindex可以同时修改行列索引，如果仅传入一个序列那么如下
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
                columns=['ohio','Texas','california'])
print(frame)

   ohio  Texas  california
a     0      1           2
c     3      4           5
d     6      7           8


In [8]:
##看看 np如何生成一个numpy.ndarray
ar = np.arange(9).reshape((3,3))
print(ar)
print(type(ar))
print(ar.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>
(3, 3)


In [9]:
# 　c：使用colunms重新索引列
states=['Texax','Utah','california']
frame.reindex(columns=states)

Texax  Utah  california
a    NaN   NaN           2
c    NaN   NaN           5
d    NaN   NaN           8

In [10]:
# d:同时插入行列，但是插值只能按行应用
#同时对行 列进行重新索引 而插值只能引用到行
frame.reindex(index=['a','b','c','d'],method='ffill',
              columns=states)

Texax  Utah  california
a    NaN   NaN           2
b    NaN   NaN           2
c    NaN   NaN           5
d    NaN   NaN           8

In [13]:
index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
df = pd.DataFrame({
     'http_status': [200,200,404,404,301],
     'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
      index=index)
df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

In [14]:
new_index= ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10',
            'Chrome']
df.reindex(new_index)

http_status  response_time
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

In [15]:
df.reindex(new_index, fill_value=0)
df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

#### 2 丢弃制定轴上的项

In [17]:
##### a:drop方法返回一个指定轴上删除了指定值的新对象，删除列c
#丢弃指定轴的项
obj=Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj=obj.drop('c')
new_obj


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [18]:
# 　　b：删除两个 b c
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [20]:
# c：对于dataframe可以删除任意轴上的索引
#对于DataFrame可以删除任意轴的索引
data = DataFrame(np.arange(16).reshape((4,4)),
                 index=['ohio','colorado','utah','new york'],
                   columns=['one','two','three','four'])
print(data)
#删除两个
data.drop(['colorado','ohio'])

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15


one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

#### 3 索引，选取和过滤

In [22]:
# a:Series中的索引类似于Numpy，但是不只是整数，索引也可以是字符
obj=Series(np.arange(4.),index=['a','b','c','d'])
obj['b']#1.0

1.0

In [25]:
# b：按照整数，范围
print(obj[1])#1.0
print(obj[2:4])# 2 3

1.0
c    2.0
d    3.0
dtype: float64


In [31]:
# 　c：利用标签的切片运算和普通的python切片不同，其包含末端
obj['a':'c']#a b c d 0 1 2 3

a    0.0
b    1.0
c    2.0
dtype: float64

In [32]:
# 　d：那么对dataframe进行索引就是获取一个或者多个列勒

data=DataFrame(np.arange(16).reshape(4,4),
           index=['ohio','colorado','mike','jason'],
                 columns=['one','two','three','four'])
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
mike        8    9     10    11
jason      12   13     14    15

In [33]:
# e：选择一列
data['two']#输出第二列

ohio         1
colorado     5
mike         9
jason       13
Name: two, dtype: int64

In [34]:
#f：选择多列
data[['three','one']]

three  one
ohio          2    0
colorado      6    4
mike         10    8
jason        14   12

In [98]:
# g：选取行标签前两行
print(data[:2])#选取的是前面两行
## 行数
rows = data.iloc[:,0].size
print(rows)
##最后一行
print(data[(rows-1):])

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
4
       one  two  three  four
jason   12   13     14    15


In [43]:
# h：选取第三列大于5的值
data[data['three']>5]

one  two  three  four
colorado    4    5      6     7
mike        8    9     10    11
jason      12   13     14    15

In [45]:
#i：为了能在dataframe的行上进行标签索引引入字段ix
data.ix['colorado',['two','three']]

two      5
three    6
Name: colorado, dtype: int64

In [55]:
# j：选取第4 1 2列 而且行为colorado jason
data.ix[['colorado','jason'],[3,0,1]]

four  one  two
colorado     7    4    5
jason       15   12   13

In [74]:
print(data.ix[:,1:3])
print(data.ix[['colorado','jason'],[1,2]])

          two  three
ohio        1      2
colorado    5      6
mike        9     10
jason      13     14
          two  three
colorado    5      6
jason      13     14


In [99]:
# k：输出行mike
print(data.ix[2])
##某个元素 
print(data.ix[2,2])

one       8
two       9
three    10
four     11
Name: mike, dtype: int64
10


In [ ]:
#### DataFrame索引总结
obj.ix[:,val]      选取单个列或列子集
obj.ix[val1,val2]  同时选取行和列
reindex方法        将一个或多个轴匹配到新索引
xs方法             根据标签选取单行或单列，并且返回一个Series
icol、irow方法     根据整数位置选取单列或单行，并返回一个Series
get_value、set_value方法  根据行标签和列标签选取单个值


#### 4 算数运算和数据对齐

In [77]:
# 　a:Series的加法
s1=Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
print(s1)
print(s2)
print(s1+s2) #加上NAN结果还是NAN

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64
a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [79]:
# b:对于dataframe，对齐会同时发生在行 列中
df1=DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
              index=['utah','ohio','colorado'])
df2=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
              index=['utah','ohio','colorado','oragen'])
print(df1)
print(df2)
print(df1+df2) # ------>索引和列都为其并集

            b    c    d
utah      0.0  1.0  2.0
ohio      3.0  4.0  5.0
colorado  6.0  7.0  8.0
            b     d     e
utah      0.0   1.0   2.0
ohio      3.0   4.0   5.0
colorado  6.0   7.0   8.0
oragen    9.0  10.0  11.0
             b   c     d   e
colorado  12.0 NaN  15.0 NaN
ohio       6.0 NaN   9.0 NaN
oragen     NaN NaN   NaN NaN
utah       0.0 NaN   3.0 NaN


In [ ]:
# 　c：在算术方法中填充值。比如说两个dataframe相加，其中一个不在的时候填充为0

In [82]:
#算术中进行填充
df1=DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
print(df1)
print(df2)
print(df1+df2) 
#使用df1的add方法 传入df2以及一个fill_value参数
df1.add(df2,fill_value=0)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

#### 5 DataFrame和Series之间的运算----->广播，也就是如果第一个数值-1，那么这个列都会减1

In [86]:
# a：看一看一个二维数组和一行之间的差
arr=np.arange(12.).reshape((3,4))
print(arr)
arr-arr[0]

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]


array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [94]:
# b:frame和series的运算
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                index=['utah','ohio','texas','orogen'])
series=frame.ix[0] #第0行
print(frame)
print(series)
print(frame-1)   # ---->广播，也就是如果第一个数值-1，那么这个列都会减
print(frame-series)

          b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
orogen  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: utah, dtype: float64
          b    d     e
utah   -1.0  0.0   1.0
ohio    2.0  3.0   4.0
texas   5.0  6.0   7.0
orogen  8.0  9.0  10.0
          b    d    e
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
orogen  9.0  9.0  9.0
